---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webapp-secret
  namespace: webapp-dev
spec:
  encryptedData:
    API_KEY: AgCQ8OF63zQnUYPfAcyztz1pqTx7VQGSew4dovHarGCyeqSBQ6ZHPp2IEhtjSuFqxGJcdEcyc88P3rg0v7p+r0SYKj71OPtGjm7Exq37mQGCFzinJ5z7ajQ35Yvv/1UFIILX3ez5RWbzRsKHxDEke/gelxw3pdiObiWpp2Mycn9DKpFc9/PMQ8UgQhqidybpuWDr7r/cSxRLMg7Por4O7AKQrw2QRfnGtZ7Jzwd+cg5ApZZGZf7pelv5MqnybGRRvswXfR5DjpuRQ6gLt0ydkFF4wmn4B3oToiPU+sqSRGjmFZsUMJcSYiaexl8EBBcvum8kR2e6yWt/nlbsdtCUbVjC9ujwXRWPy6iAyF3PTWiJQpjJ4mDu9U1W1I/eLk4JGjrP0k4oHwTGBn33yVLmJGJG92yTLMM4zsrnuXYexIDn9NFgMwlFEL8pzalaQE2aDMNR4KGrjPuJTXAS13pFpTINYqS9JADtUF6vvOiUs5JkN6mf12MvQfrRjmPwq7nMr3zgyQ3Ua5M+lpEuO02766nG+lYM6Rhn3y3ga1OvU8eWAqLAmp4UBBzHZI0QRRt4TmIg/NshGH7n3HTpBLxohaZ9ErfxLJH/fudTx8Dr/+RmRm5VQWHWCfFCuP+B61G9y2Zl433ZDQ9fD0tFW+RmTWXJDSvifCNYQcwc2y03C/9ZwPNOrHL4pTGnRErMpK7r6hTli84s4Z6WOVsNunUG1o4hO/ddCLc=
  template:
    metadata:
      name: webapp-secret
      namespace: webapp-dev
