apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision:  92.1.0 
    helm:
      releaseName: kps
      valuesObject:
        alertmanager:
          enabled: false
        nodeExporter:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeProxy:
          enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
          resources:
            requests: { cpu: 25m, memory: 64Mi }
            limits: { cpu: 100m, memory: 160Mi }
        prometheus:
          prometheusSpec:
            retention: 6h
            retentionSize: 1GB
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            resources:
              requests: { cpu: 100m, memory: 300Mi }
              limits: { cpu: 500m, memory: 600Mi }
        grafana:
          resources:
            requests: { cpu: 25m, memory: 100Mi }
            limits: { cpu: 200m, memory: 250Mi }
        kube-state-metrics:
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits: { cpu: 100m, memory: 100Mi }
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
